dist: trusty
language: python

cache: pip
cache:
    directories:
        - '$HOME/.sonar/cache'
python:
    - "3.5"

addons:
    sonarcloud:
        organization: "burrch3s-github"

install:
    - pip install -r requirements.txt

script:
    - green
    - coveralls
    - sonar-scanner
